### ISSUE TITLE
Scan ledger/trezor for addresses with eth or rep balances.

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur-ui#2509] opened 2018-11-29 23:37 UTC
Instead of showing pages of addresses with zero balance, scan through derivation paths to find addresses with eth and/or rep.
User can still use advanced to set any cutom derivation path.

**Comment by adrake33** [comment] 2018-11-30 23:50
Dupe of https://github.com/AugurProject/augur/issues/288

**Closed by adrake33** 2018-11-30 23:50 UTC
Labels: Feature, Priority: Medium, Release 1.9.0, v1
